variables:
  IMAGE_NAME: "gitlab.inalogy.com:5050/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  CI_REGISTRY: "gitlab.inalogy.com:5050"
  MP_VERSION: "4.8.8"
  MP_DOCKER_TAG: "4.8.8-alpine"

stages:
  - build

build-image:
  stage: build
  tags:
    - static
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker buildx use multi-builder
    - docker buildx build --push --platform linux/amd64,linux/arm64 \
      -t $IMAGE_NAME:$MP_DOCKER_TAG \
      --build-arg MP_VERSION=$MP_VERSION \
      --build-arg base_image=alpine \
      --build-arg base_image_tag=latest .
  only:
    - main    
  when: manual
