name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      MP_VERSION:
        description: 'Version of MidPoint'
        required: true
        default: '4.8.8'
      MP_DOCKER_TAG:
        description: 'Docker tag to use'
        required: true
        default: '4.8.8-alpine'

env:
  IMAGE_NAME: inalogy/midpoint

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: gitlab.inalogy.com:5050
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_JOB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker buildx build --push --provenance=false \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.IMAGE_NAME }}:${{ github.event.inputs.MP_DOCKER_TAG }} \
            --build-arg MP_VERSION=${{ github.event.inputs.MP_VERSION }} \
            --build-arg base_image=alpine \
            --build-arg base_image_tag=latest \
            .

